### PR TITLE
Resolves #167 

### LINKED ISSUE #167: Loading winch connected same vessel
Loading a vessel with a winch connected to a CC-R2 port (presumably possible with other connectors) on the same vessel (like this http://i.imgur.com/RKQxkmQ.png) causes the physical connection to break and leaves the port and winch unable to be used properly (they think they are connected still).

There is a simple work-around:

_Method:_
KASModuleWinch.OnVesselGoOffRails()

_Block:_
if (headState == PlugState.PlugUndocked && fromSave) {}

_LN 474:_ PlugHead(connectedPortInfo.module, PlugState.PlugUndocked, true, false);

as "Already docked" evals to "false" in PlugHead() and it exits the method.

_Change LN 474 to:_ PlugHead(connectedPortInfo.module, PlugState.PlugUndocked, true, false**, true**);

I know this by-passes some checking in PlugHead(), but in simple testing it seems to keep port-winch connections after a load. Works around issues #148  and seems to fix issue #147

### PR DESCRIPTION
**Pull request by Conceit**
Resolves loading issues with ports that are plugged but not docked. Needs more testing (works for me).

### CODE REVIEW

**Comment by ihsoft** [comment]
This fix seems to help but I'm not confident it's the right approach to fix the issue. Let me go thru the code to figure out what may be the root cause.

**Comment by Conceit** [comment]
You're right, the root cause is deeper: It seems to me, that the redundant data persistency of the plug's "plugged" flag is the actual cause. This flag gets also restored by the winch (during plugHead in OnVesselGoOffRails), its additional persistency reqiures for additional checks which are error-prone (e.g. too many checks, like here): The plug gets restored first (plugged=true), when the winch gets restored and plugged, the plug's status must be checked. But not, if it was fromSave...

In my opinion,  "KASModPlug.plugged" should not be persistent at all. But I'm still testing -> Currently I'm refactoring the whole winch, including removal of several data-redundancies. Give me some time for clean-up and testing, and I will contribute a bunch of brushed-through spaghetti code.

**Comment by ihsoft** [comment]
Sounds good. When you'll be doing the refarctoring please keep commits logically isolated and as short as possible. It's ok to have many short commits, it's not ok to have one or two big "do it all" commits. Such changes are hard to review.

**Comment by Conceit** [comment]
So, some intermediate status.

Things done:
- refactored all deploy/plug/dock related things into private functions that follow simple guidelines:
    * no sanity checks (they're done in public fns, so checks are not in the way for new features)
    * clear functionality (deployHead, well, just deploys the head, plugHead plugs it in, dockHead switches to dock mode, undockHead, unplugHead, lockHead etc)
- made public API-style calls (garantee sanity by parameter and status checks), e.g. "Plug(port)" will check if port ist valid, if already deployed (and deploy if not) and so on.
- removed persistency of the port's "plugged" state, which resolved a lot of spaghetti (all fromSave checks can be omitted), works pretty well so far
- By that I removed a bug that I introduced myself (sorry!) - the GUI's undock toggle might crash the fun out of it. That wasn't clear to me in the original code (that's why I wanted to refactor) and I didn't see it in testing, 
- used a boolean "silent" in all functions to suppress sound AND visual output (it resembles the functionality formerly done by multiple flags).
- Many little code-beauty tweaks (regions, renaming...)
- Tested a lot...

Current state:
- Next to the above told, there is on small bug (after loading, the cable lenght is not set correctly, one call to cableRealLength flushed out of the code path somehow) - Will check on next weekend.
- Tested plugging, docking (head), docking (winch), retracting a winch-docked vessel, toggle docking, load, save, time warp. Looks good so far.

Things to do:
- Changing more functions to private (or protected)
- change order of functions for better legibility
- refactor motor / winch control (minor things, should be easy)
- refactor and overhaul file loading pattern (see questions below)
- more testing
- rebase fixups (that's why I don't have it in my fork on github, don't want to rebase after pushing)

Questions:
- Should internal stuff be private or rather be protected. It depends a bit on how you expect extensions to occur. Private might limit functionality for other mods, but is beneficial to keep sane states in the winch. Protected may allow other mods to inherit and also use internal functionalities. Opinions?

- Indenting is annoying für VS users, but changing indentation means commiting whole source-code again and might break the experience for other coders. Personally, I consider C# as a M$/Visual Studio language and prefer their indenting scheme. Should we change it to VS style?

- Loading plugs and winches is spread over multiple functions (onLoad, onStart, parallel working WaitAndLoad, OnVesselGoOffRails and finally PlugHead). I would like to overhaul that, but I'm not entirely sure about the consequences (not a Unity or KSP dev). Can someone explain me details about OnVesselGoOffRails (when called for what purpose, why winch-head plugging done here), etc.

**Comment by ihsoft** [comment]
Have you tested your changes with 1.1.3? Winch head physics is totally broken there.

> Should internal stuff be private or rather be protected

If method is *designed* to be overriden then it should be protected or public. Otherwise, it must be private. It's hard to give clear rules when do what but in general if you haven't invested efforts into designing class inheritance then there should be no protected methods. Common mistake is making methods protected "just in case", assuming somone may want overriding them. It's always a bad approach.

> Should we change it to VS style?

I'd like to keep it (https://github.com/KospY/KAS/blob/master/Plugins/Source/README.md). It's been a while since I used VS last time but I remember it offers pretty good tools to customize code style. I'm sure not 100% of the style requirements can be setup in the IDE but some extra efforts to fix wrong auto indentation during the coding pay off very quickly in the product maintenance. Given I spend more time in the code than in the game for me, personally, it does matter. I'd suggest the only thing that cannot be configured is 4 space indentation on line wrapping, not a big deal IMO.

> Can someone explain me details about OnVesselGoOffRails (when called for what purpose, why winch-head plugging done here), etc.

I'm not a big expert either. This method is usually used when some vessel scope work needs to be done right before vessel's activation in the game. Not sure if it's a right approach but it worked so far. Methods of `PartModule` can be called in different order in editor and in flight, and some can be duplicated (e.g. `OnLoad`), so I would not count in them.

**Comment by ihsoft** [comment]
FYI. I've started working on KAS 1.0 which is a complete redesign of the code. v0.5.9 will live in parallel for some time after the v1.0 release (~1 month to complete v1.0, plus 3-5 months to let legacy parts migrated). If you haven't completed the refactoring yet _and_ the amount efforts to complete it is big enopugh then you may consider abandoning the work altogether.

**Comment by Conceit** [comment]
Hi, thanks for the info.. I've gotten pretty far, but incorporating current changes of master into an parallel dev'd refactored branch would be a lot of work (conflicts everywhere). I've gotten pretty far with much effort and tested a lot. It's not perfect as of yet (currently debugging), but I think it's a big step forward. So maybe this here is a good opportunity: Please take a look at my current status here: https://github.com/Conceit/KAS/tree/refactor - if you like the way it goes and think you would like to merge this into 1.0, we could coordinate ourselves a bit and I can take over some tasks.

**Comment by ihsoft** [comment]
An initial design of the change you may see here: https://github.com/KospY/KAS/tree/KAS-v1.0. It's not final, there will be a lot of changes before the release. In the new design the winch will be a link _source_ for the port's _target_. It's good question what will be winch head: it can be "an internal stuff" as for now, or it can be an internal part that is _target_ for the winch and _source_ for the port. I'd choose the latter.

**Pull request merged**
